version: "3.9"

services:
  react-app:
    build: .
    ports:
      - "3000:5173"
    volumes:
      - .:/app             # Monte ton code source pour hot reload
      - /app/node_modules  # Empêche d'écraser node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Pour que React détecte les changements dans Docker (surtout sur WSL/Windows)
